### PR TITLE
Add encrypted data bag support

### PR DESCRIPTION
**Pull request by shortdudey123**
Allows MMS api key to be loaded from an encrypted data bag

### CODE REVIEW

**Comment by sunggun-yu** [comment]
Hi @shortdudey123 
Thank you for the PR!

I also assumed to use data bag for critical data. however, my decision was to let people to use wrapper for there own purpose. I'd like keep the cookbook as simple as possible.
how do you think?

**Comment by shortdudey123** [comment]
You can't use a wrapper cookbook and still stay secure.  If you load from an encrypted data bag or vault, how do you get the data into the template w/o using attributes?

**Comment by shortdudey123** [comment]
@sunggun-yu any update on your side?

**Comment by shortdudey123** [comment]
@sunggun-yu any updates?

**Comment by sunggun-yu** [comment]
@shortdudey123 
Hi, I'm so sorry about delaying this PR. I'm trying to write some example for this issue.
please give me few more days.
and, not to create the dependency of data bag is one of my goal on this cookbook. please understand.

**Comment by shortdudey123** [comment]
> trying to write some example for this issue

Can you elaborate on what you mean?

>  not to create the dependency of data bag

This is not a dependency since it is optional as seen [here](https://github.com/shortdudey123/chef-mongodb3/blob/add_encrypted_data_bag_support/recipes/mms_automation_agent.rb#L20-L27)

**Comment by shortdudey123** [comment]
@sunggun-yu any updates on your end? Would love to have this merged / dealt with since its over 100 days old

**Comment by shortdudey123** [comment]
@sunggun-yu any updates on your end?

**Comment by sunggun-yu** [comment]
@shortdudey123 
I'm so sorry for late reply.

I added test wrapper cookbook. please check : https://github.com/sunggun-yu/chef-mongodb3/blob/develop/test/cookbooks/mongodb3-test/recipes/mms_automation_agent_with_data_bag.rb

this test cookbook set the attribute from encrypted data bag. 

Thank you.

**Comment by shortdudey123** [comment]
That does not solve the original problem
The api key is still stored clear text...

**Comment by shortdudey123** [comment]
@sunggun-yu any reason to not be secure?

**Pull request closed without merging**
