### PR TITLE
Make keyserver configurable and fix faraday (berkshelf version bump)

### PR DESCRIPTION
**Pull request by dennisvink**
Allow for the default keyserver.ubuntu.com keyserver override.

### CODE REVIEW

**Comment by dennisvink** [comment]
The new faraday gem is incompatible with Berkshelf 3.x. I've bumped the version to ~> 4.0.0 to resolve this.

**Comment by sunggun-yu** [comment]
Thank you for the PR!

**Comment by sunggun-yu** [comment]
Hi, @megamoth !

Thank you for your PR. and, I have question for this PR.
I'm just curios, Is there any specific reason that make it configurable?

**Comment by dennisvink** [comment]
Greetings @sunggun-yu !

I've made it configurable to be able to continue with deploys when the default keyserver is down. It's not an uncommon occurance :-P

**Comment by sunggun-yu** [comment]
Thank you for your explanations. 
I'll merge it. however, I'll change some portion of it. I've decided to provide it as `['mongodb3']['package']['repo']` attribute in order to make it configurable. it will be worth to resolve #10 like issues.

**Comment by sunggun-yu** [comment]
opps, I confused, I'm not saying about keyserver. I'm saying about uri. sorry for make you confused.

**Pull request merged**
